#!/usr/bin/env python3
"""
Sync/check derived agent entrypoint docs from AGENTS.md.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
CANONICAL = REPO_ROOT / "AGENTS.md"
TARGETS = [
    REPO_ROOT / "CLAUDE.md",
    REPO_ROOT / "GEMINI.md",
]
BANNER = "<!-- AUTO-GENERATED FROM AGENTS.md. DO NOT EDIT THIS FILE DIRECTLY. -->\n\n"


def _normalize_newlines(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def _read_canonical() -> str:
    if not CANONICAL.exists():
        print(
            f"Required file missing: {CANONICAL.relative_to(REPO_ROOT)}.",
            file=sys.stderr,
        )
        print("Set up `AGENTS.md` in the repo root before running sync/check.", file=sys.stderr)
        raise SystemExit(1)

    try:
        return _normalize_newlines(CANONICAL.read_text(encoding="utf-8"))
    except OSError as exc:
        print(
            f"Unable to read {CANONICAL.relative_to(REPO_ROOT)}: {exc}.",
            file=sys.stderr,
        )
        print("Fix file permissions/path issues and retry.", file=sys.stderr)
        raise SystemExit(1)


def _is_symlinked_to_canonical(target: Path) -> bool:
    if not target.is_symlink():
        return False
    try:
        return target.resolve() == CANONICAL.resolve()
    except OSError:
        return False


def _expected_content() -> str:
    canonical_text = _read_canonical().strip("\n")
    return f"{BANNER}{canonical_text}\n"


def sync() -> int:
    expected = _expected_content()
    for target in TARGETS:
        if _is_symlinked_to_canonical(target):
            print(
                f"Skipping {target.relative_to(REPO_ROOT)} (symlink to AGENTS.md). "
                "Keep symlink mode for local use or run --restore-copies."
            )
            continue
        target.write_text(expected, encoding="utf-8")
        print(f"synced: {target.relative_to(REPO_ROOT)}")
    return 0


def check() -> int:
    expected = _expected_content()
    mismatches: list[str] = []

    for target in TARGETS:
        rel = str(target.relative_to(REPO_ROOT))
        if _is_symlinked_to_canonical(target):
            continue
        if not target.exists():
            mismatches.append(f"{rel}: missing")
            continue
        current = _normalize_newlines(target.read_text(encoding="utf-8"))
        if current != expected:
            mismatches.append(f"{rel}: out of sync")

    if mismatches:
        print("Entrypoint docs are not in sync with AGENTS.md:", file=sys.stderr)
        for line in mismatches:
            print(f"- {line}", file=sys.stderr)
        print(
            "Run `python3 scripts/sync_entrypoint_docs.py --sync` and commit the results.",
            file=sys.stderr,
        )
        return 1

    print("Entrypoint docs are in sync with AGENTS.md.")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Sync/check derived entrypoint docs.")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--sync", action="store_true", help="Rewrite derived docs from AGENTS.md")
    mode.add_argument("--check", action="store_true", help="Fail if derived docs are out of sync")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.sync:
        return sync()
    return check()


if __name__ == "__main__":
    raise SystemExit(main())
